/*
 * Sign DEVICES
 * Types of sign devices
 * - TREZOR: https://trezor.io/
 * - LEDGER: https://www.ledger.com/
 * - MOBILE_APP: Will be developed later by https://Asylia.io
 * - ASYLIA: Auto generated public and private keys by Asylia app based on user quorum and filled required keys
 */
export const SIGN_DEVICES_LIST = Object.freeze({
  TREZOR: 'TREZOR',
  LEDGER: 'LEDGER',
  MOBILE_APP: 'MOBILE_APP',
  ASYLIA: 'ASYLIA',
});

export const EMPTY_SIGN_DEVICE_METHOD = null;
export type EmptySignDeviceMethod = typeof EMPTY_SIGN_DEVICE_METHOD;
export type SignDevicesListType = keyof typeof SIGN_DEVICES_LIST | EmptySignDeviceMethod;

/*
 * Public keys in the wallet
 * - Type for extended public key
 * - Empty object for extended public key => user will be asked to collect the key
 * - Asylia key will be used for the Asylia wallet => will be generated by the Asylia app after user adds all required the keys
 */
export type WalletExtendedPublicKey = {
  name: string;
  bip32Path: string;
  xpub: string;
  xfp: string;
  method: SignDevicesListType;
};

export const EMPTY_WALLET_EXTENDED_PUBLIC_KEY: WalletExtendedPublicKey = {
  name: '',
  bip32Path: '',
  xpub: '',
  xfp: '',
  method: null,
};

export const EMPTY_WALLET_ASYLIA_EXTENDED_PUBLIC_KEY: WalletExtendedPublicKey = {
  name: '',
  bip32Path: '',
  xpub: '',
  xfp: '',
  method: SIGN_DEVICES_LIST.ASYLIA,
};
